sonar.projectKey=pollo-30
sonar.projectName=Proyecto Donaciones
sonar.projectVersion=1.0

sonar.sources=src,backend/src
sonar.tests=backend/tests
sonar.test.inclusions=**/*.test.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/public/**,**/fotos/**,**/*.css
sonar.coverage.exclusions=**/*.test.js,**/src/main.jsx,**/src/App.jsx,**/src/base-de-datos/mockData.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.log.level=INFO